name: flick_view
description: Flick View for Desktop

version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.3
  path: ^1.8.3
  easy_sidemenu: ^0.5.0
  mime: ^1.0.4
  path_provider: ^2.1.1
  dio: ^5.3.2
  archive: ^3.3.7

  media_kit: ^1.1.5
  media_kit_video: ^1.1.6
  media_kit_libs_video: ^1.0.1
  media_kit_native_event_loop: ^1.0.7
  media_kit_libs_android_video: ^1.3.2
  media_kit_libs_ios_video: ^1.1.3
  media_kit_libs_macos_video: ^1.1.3
  media_kit_libs_windows_video: ^1.0.7
  media_kit_libs_linux: ^1.1.1

  get: ^4.6.5

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 7812516a5c1fc8ef379e244106953a2b534432b9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  flutter_launcher_icons: "^0.10.0"

flutter:
  assets:
    - assets/icon/
    - assets/images/
    - assets/test/
  uses-material-design: true

fonts:
  - family: Pretendard
    fonts:
      - asset: assets/font/Pretendard/Pretendard-ExtraLight.otf
        weight: 200
      - asset: assets/font/Pretendard/Pretendard-Light.otf
        weight: 300
      - asset: assets/font/Pretendard/Pretendard-Regular.otf
        weight: 400
      - asset: assets/font/Pretendard/Pretendard-Medium.otf
        weight: 500
      - asset: assets/font/Pretendard/Pretendard-SemiBold.otf
        weight: 600
      - asset: assets/font/Pretendard/Pretendard-Bold.otf
        weight: 700
      - asset: assets/font/Pretendard/Pretendard-Black.otf
        weight: 900

  
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"
#  min_sdk_android: 21
#  web:
#    generate: true
#    image_path: "assets/icon/icon.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "assets/icon/icon.png"
#    icon_size: 48